_default_section:
  root_authority: root_authority
  revocation_list: revocation_list
  sign_request: authority

root_authority:
  kind: certificate
  signature_algorithm: sha256
  duration:
    years: 10
  distinguished_name:
    - o: Acme Corporation
    - cn: Acme Corporation Authority
  extensions:
    basicConstraints:
      critical: true
      ca: true
#      pathLenConstraint: 0
    keyUsage:
      critical: true
      usages:
        - cRLSign
        - keyCertSign
    subjectKeyIdentifier:
      critical: false
      value: subject_hash
    # By RFC 5280, when "a CA distributes its public key in the form of a 'self-signed'
    # certificate, the authority key identifier MAY be omitted" (see 4.2.1.1).

revocation_list:
  kind: revocation_list
  signature_algorithm: sha256
  duration:
    days: 180

authority:
  kind: sign_request
  signature_algorithm: sha256
  duration:
    years: 5
  extensions:
    subjectKeyIdentifier:
      action: add
      critical: false
      value: subject_hash
    authorityKeyIdentifier:
      action: add
      critical: false
      keyIdentifier: issuer_hash
    basicConstraints:
      forced_critical_value: true
    keyUsage:
      forced_critical_value: true
    crlDistributionPoints:
      critical: false
      distributionPoints:
        - fullName:
                # By RFC 5280, the "URI MUST point to a single DER encoded CRL as specified
                # in [RFC2585]" (see 4.2.1.13).
                # (Also, the mime type should be 'application/pkix-crl'.)
            - URI: http://pki.acme.corp/acme.crl
    authorityInfoAccess:
      critical: false
      accessDescriptions:
        - caIssuers:
              # By RFC 5280, the "the URI MUST point to either a single DER encoded certificate as
              # specified in [RFC2585] or a collection of certificates in a BER or DER encoded
              # 'certs-only' CMS message as specified in [RFC2797]" (see 4.2.2.1).

              # For a single certificate (with mime type 'application/pkix-cert'):
            URI: http://pki.acme.corp/acme.cer
              # Or for multiple certificates (with mime type 'application/pkcs7-mime'):
              #URI: http://pki.acme.corp/acme.p7c
        - ocsp:
            URI: http://oscp.acme.corp/


